### ISSUE TITLE
How to use with Laravel?

### ISSUE THREAD

**Issue by Jackardios** [sherifabdlnaby/phpdocker#10]
When I use this along with laravel nginx shows an error:
`Warning: require(/var/www/app/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/app/public/index.php on line 34`
As I understand it, this happens because only the public folder is copied for the nginx container. Should I add the entire laravel folder as a volume for nginx or can it be done differently?

**Comment by Jackardios** [comment]
solved the problem, it was my mistake

**Comment by sherifabdlnaby** [comment]
@Jackardios Glad you solved it, I just saw the issue and would have loved to help.

Mind sharing what was the issue to help anyone who has made a similar mistake?

**Comment by Jackardios** [comment]
@sherifabdlnaby the project had an empty vendor folder and since it existed the `composer install` command was not executed
